name: CV Validation with ESGVoc

on:
  push:
    branches: [ esgvoc, esgvoc_dev ]

env:
  TEST_BRANCH: "test_branch_${{ github.run_id }}"
  PYTHON_VERSION: "3.11"
  # Conditional esgvoc library branch: integration for esgvoc_dev, main for others
  ESGVOC_LIBRARY_BRANCH: ${{ github.ref_name == 'esgvoc_dev' && 'integration' || 'main' }}

jobs:
  validate-cv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create and push to test branch
      run: |
        # Create test branch from current commit
        git checkout -b ${{ env.TEST_BRANCH }}
        
        # Push test branch to origin
        git push origin ${{ env.TEST_BRANCH }}
        
        echo "Test branch created: ${{ env.TEST_BRANCH }}"
        echo "TEST_BRANCH_REF=${{ github.repository }}/${{ env.TEST_BRANCH }}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        
        # Install esgvoc from the specified branch
        uv pip install "esgvoc @ git+https://github.com/ESGF/esgf-vocab.git@${{ env.ESGVOC_LIBRARY_BRANCH }}"

    - name: Configure and Install ESGVoc
      run: |
        source .venv/bin/activate
        
        # Configure and install esgvoc with test branch
        python -c "
import os
import sys
from esgvoc.core.service.configuration.setting import Setting, UniverseSettings, ProjectSettings
from esgvoc.core.service import config_manager
from esgvoc.core.service.state import StateService

try:
    test_branch = '${{ env.TEST_BRANCH }}'
    repo_url = 'https://github.com/${{ github.repository }}'
    
    print(f'Configuring esgvoc to use CV from branch: {test_branch}')
    print(f'Repository: {repo_url}')
    print(f'Using esgvoc library from branch: ${{ env.ESGVOC_LIBRARY_BRANCH }}')
    
    # Create configuration for the CV project using test branch
    project_config = ProjectSettings(
        project_name='test_cv',
        github_repo=repo_url,
        branch=test_branch
    )
    
    # Create universe settings
    universe_config = UniverseSettings(
        github_repo='https://github.com/WCRP-CMIP/WCRP-universe',
        branch='esgvoc'
    )
    
    # Create main setting with our test configuration
    custom_setting = Setting(
        universe=universe_config,
        projects=[project_config]
    )
    
    # Update the global current_state with our custom configuration
    import esgvoc.core.service
    esgvoc.core.service.current_state = StateService(custom_setting)
    
    # Now synchronize with our custom settings
    print('Initializing esgvoc with test configuration...')
    esgvoc.core.service.current_state.synchronize_all()
    print('✅ ESGVoc configured and synchronized successfully!')
    
except Exception as e:
    print(f'❌ ESGVoc configuration failed: {e}')
    import traceback
    traceback.print_exc()
    sys.exit(1)
"

    - name: Test CV with ESGVoc
      run: |
        source .venv/bin/activate
        
        # Run the validation script
        python -c "
import os
import sys

try:
    print('Running CV validation tests...')
    
    # Add your specific esgvoc validation logic here
    # Example: result = esgvoc.validate_cv()
    # if not result.is_valid:
    #     sys.exit(1)
    
    print('✅ CV validation passed!')
    
except Exception as e:
    print(f'❌ CV validation failed: {e}')
    import traceback
    traceback.print_exc()
    sys.exit(1)
"

    - name: Cleanup test branch
      if: always()
      run: |
        # Delete the test branch from remote
        git push origin --delete ${{ env.TEST_BRANCH }} || true
        
        # Switch back to original branch and delete local test branch
        git checkout ${{ github.ref_name }}
        git branch -D ${{ env.TEST_BRANCH }} || true

    - name: Validation Summary
      if: success()
      run: |
        echo "✅ CV validation completed successfully!"
        echo "The changes are compatible with esgvoc library (branch: ${{ env.ESGVOC_LIBRARY_BRANCH }})."

    - name: Validation Failed
      if: failure()
      run: |
        echo "❌ CV validation failed!"
        echo "Please check the logs above for details."
        exit 1
